spring.application.name=quiz
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION}

server.port=8080
spring.jackson.serialization.write-dates-as-timestamps=false
frontend.url=${FRONTEND_URL}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

groq.api.key=${GROQ_API_KEY}
groq.api.url=${GROQ_API_URL}
groq.model=${GROQ_MODEL}

server.max-http-request-header-size=${SERVER_MAX_HEADER}
